// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-two/route.tsx
// mounts: /home/shared-two, /about/shared-two
import { makeSharedRoute } from "../../../sharedRoutes.gen";

type MountFilePaths = "/home/shared-two" | "/about/shared-two";

export const shared = makeSharedRoute<MountFilePaths>(
  [
  "/home/shared-two",
  "/about/shared-two",
  ],
  "src/routes/home/shared-two/route",
);
