// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/-shared-two/route.tsx (mount: src/routes/home/shared-two.mount.ts)
import type { Register } from '@tanstack/react-router'
import { createFileRoute } from '@tanstack/react-router'
import { shared } from '../../-shared-two/route'

type T = (typeof shared)['~types']

export const Route = createFileRoute('/home/shared-two')<
  Register,
  T['searchValidator'],
  T['params'],
  T['routeContextFn'],
  T['beforeLoadFn'],
  T['loaderDeps'],
  T['loaderFn'],
  unknown,
  T['ssr'],
  T['middlewares'],
  T['handlers']
>({ ...shared.options } as any)
