// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/-shared-two/route.tsx
// mounts: /about/shared-two, /home/shared-two
import { makeCreateSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/about/shared-two" | "/home/shared-two";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
   ["/about/shared-two", "/home/shared-two"],
   "src/routes/-shared-two/route",
);
