// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-one/$sharedOneChild/route.tsx (mount: src/routes/home/$sharedOneChild.mount.ts)
import type { Register } from '@tanstack/react-router'
import { createFileRoute } from '@tanstack/react-router'
import type { SourceRouteTypes } from '../../../sharedRoutes.gen'
import { patchSharedHooks } from '../../../sharedRoutes.gen'
import { Route as shared } from '../shared-one/$sharedOneChild/route'

patchSharedHooks(shared, ['/home/shared-one/$sharedOneChild', '/about/$sharedOneChild', '/about/shared-one/$sharedOneChild', '/home/$sharedOneChild'])

type T = SourceRouteTypes<typeof shared>

export const Route = createFileRoute('/home/$sharedOneChild')<
  Register,
  T['searchValidator'],
  T['params'],
  T['routeContextFn'],
  T['beforeLoadFn'],
  T['loaderDeps'],
  T['loaderFn'],
  unknown,
  T['ssr'],
  T['middlewares'],
  T['handlers']
>({ ...shared.options } as any)
