// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/modal/open.tsx (mount: src/routes/help/modal.mount.ts)
import type { Register } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import type { SourceRouteTypes } from "../../../sharedRoutes.gen";
import { patchSharedHooks } from "../../../sharedRoutes.gen";
import { Route as shared } from "../../modal/open";

patchSharedHooks(shared, ["/modal/open", "/help/modal/open", "/inventory/help/modal/open"]);

type T = SourceRouteTypes<typeof shared>;

const {
   id: _id,
   path: _path,
   getParentRoute: _getParentRoute,
   ...sourceOptions
} = shared.options as any;

export const Route = createFileRoute("/help/modal/open")<
   Register,
   T["searchValidator"],
   T["params"],
   T["routeContextFn"],
   T["beforeLoadFn"],
   T["loaderDeps"],
   T["loaderFn"],
   unknown,
   T["ssr"],
   T["middlewares"],
   T["handlers"]
>({ ...sourceOptions });
