// Generated by tanstack-shared-routes. Do not edit.
// source: src/shared/providers/$providerId.tsx (mount: src/routes/inventory/providers.mount.ts)
import type { Register } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import { shared } from "../../../shared/providers/$providerId";

type T = (typeof shared)["~types"];

export const Route = createFileRoute("/inventory/providers/$providerId")<
  Register,
  T["searchValidator"],
  T["params"],
  T["routeContextFn"],
  T["beforeLoadFn"],
  T["loaderDeps"],
  T["loaderFn"],
  unknown,
  T["ssr"],
  T["middlewares"],
  T["handlers"]
>({ ...shared.options } as any);
