// Generated by tanstack-shared-routes. Do not edit.
// source: src/shared/providers/chart.tsx (mount: src/routes/inventory/providers.mount.ts)
import type { Register } from '@tanstack/react-router'
import { createFileRoute } from '@tanstack/react-router'
import { shared } from '../../../shared/providers/chart'

type T = (typeof shared)['~types']

export const Route = createFileRoute('/inventory/providers/chart')<
  Register,
  T['searchValidator'],
  T['params'],
  T['routeContextFn'],
  T['beforeLoadFn'],
  T['loaderDeps'],
  T['loaderFn'],
  unknown,
  T['ssr'],
  T['middlewares'],
  T['handlers']
>({ ...shared.options } as any)
