// Generated by tanstack-shared-routes. Do not edit.
// source: src/shared/providers/chart.lazy.tsx (mount: src/routes/inventory/providers.mount.ts)
import { createLazyFileRoute } from '@tanstack/react-router'
import { sharedLazy } from '../../../shared/providers/chart.lazy'

export const Route = createLazyFileRoute('/inventory/providers/chart')(sharedLazy)
