// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-two/route.tsx (mount: src/routes/home/shared-one/shared-two.mount.ts)
import type { Register } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import type { SourceRouteTypes } from "../../../../sharedRoutes.gen";
import { patchSharedHooks } from "../../../../sharedRoutes.gen";
import { Route as shared } from "../../../home/shared-two/route";

patchSharedHooks(shared, [
   "/home/shared-two",
   "/about/shared-one/shared-two",
   "/about/shared-two",
   "/home/shared-one/shared-two",
]);

type T = SourceRouteTypes<typeof shared>;

const {
   id: _id,
   path: _path,
   getParentRoute: _getParentRoute,
   ...sourceOptions
} = shared.options as any;

export const Route = createFileRoute("/about/shared-one/shared-two")<
   Register,
   T["searchValidator"],
   T["params"],
   T["routeContextFn"],
   T["beforeLoadFn"],
   T["loaderDeps"],
   T["loaderFn"],
   unknown,
   T["ssr"],
   T["middlewares"],
   T["handlers"]
>({ ...sourceOptions });
