import { createHash, randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { BANNER_SENTINEL } from "../config";

/** Sentinel that replaces the route-id literal when comparing/hashing content. */
export const ROUTE_ID_MASK = "__TSR_SHARED_ROUTES_ROUTE_ID__";

/**
 * Matches the first `createFileRoute('<id>')` / `createLazyFileRoute("<id>")`
 * call. Regex-based on purpose: both sides of every comparison were rendered
 * from our own template, so the shape is known.
 */
const ROUTE_ID_CALL_RE = /(create(?:Lazy)?FileRoute\(\s*)(["'`])((?:\\.|(?!\2).)*)\2/;

/** True when `content` was generated by this tool (banner ownership check). */
export function isOwned(content: string): boolean {
  return content.startsWith(BANNER_SENTINEL);
}

/** Returns the file's content, or `undefined` when it does not exist. */
export function readIfExists(filePath: string): string | undefined {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

/** Replaces the route-id literal of the first create(Lazy)FileRoute call with a sentinel. */
export function maskRouteIdLiteral(content: string): string {
  return content.replace(ROUTE_ID_CALL_RE, `$1$2${ROUTE_ID_MASK}$2`);
}

/** Extracts the route-id literal of the first create(Lazy)FileRoute call, if any. */
export function extractRouteIdLiteral(content: string): string | undefined {
  const match = ROUTE_ID_CALL_RE.exec(content);
  return match?.[3];
}

/** Replaces the route-id literal of the first create(Lazy)FileRoute call with `literal`. */
export function replaceRouteIdLiteral(content: string, literal: string): string {
  return content.replace(ROUTE_ID_CALL_RE, `$1$2${literal}$2`);
}

/** sha256 (hex) of the content with the route-id literal masked out. */
export function maskedHash(content: string): string {
  return createHash("sha256").update(maskRouteIdLiteral(content)).digest("hex");
}

/**
 * Writes atomically: dot-prefixed temp file in the SAME directory, then
 * rename. The dot prefix keeps the temp file invisible to the stock
 * generator's scan, and rename means the generator can never observe a
 * half-written or empty route file (it scaffolds templates into empty ones).
 */
export function atomicWrite(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  const tmpPath = path.join(dir, `.tsr-shared-${randomBytes(8).toString("hex")}.tmp`);
  try {
    fs.writeFileSync(tmpPath, content, "utf8");
    fs.renameSync(tmpPath, filePath);
  } catch (error) {
    fs.rmSync(tmpPath, { force: true });
    throw error;
  }
}
