// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/-shared-one/route.tsx
// mounts: /about/shared-one, /home/shared-one
import { makeCreateSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/about/shared-one" | "/home/shared-one";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
   ["/about/shared-one", "/home/shared-one"],
   "src/routes/-shared-one/route",
);
