// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-one/route.tsx (mount: src/routes/about/shared-one.mount.ts)
import type { Register } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import type { SourceRouteTypes } from "../../../sharedRoutes.gen";
import { patchSharedHooks } from "../../../sharedRoutes.gen";
import { Route as shared } from "../../home/shared-one/route";

patchSharedHooks(shared, ["/home/shared-one", "/about/shared-one"]);

type T = SourceRouteTypes<typeof shared>;

const {
   id: _id,
   path: _path,
   getParentRoute: _getParentRoute,
   ...sourceOptions
} = shared.options as any;

export const Route = createFileRoute("/about/shared-one")<
   Register,
   T["searchValidator"],
   T["params"],
   T["routeContextFn"],
   T["beforeLoadFn"],
   T["loaderDeps"],
   T["loaderFn"],
   unknown,
   T["ssr"],
   T["middlewares"],
   T["handlers"]
>({ ...sourceOptions });
