/**
 * Spike: generates a scaled fixture to measure type-instantiation growth.
 *   bun scripts/scale-fixture.ts shared  -> 40 shared files x 2 mounts
 *   bun scripts/scale-fixture.ts stock   -> the same 80 routes as plain stock files
 *   bun scripts/scale-fixture.ts clean   -> remove everything it created
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const N = 40;
const mode = process.argv[2];

const sharedDir = (i: number) => path.join(root, `src/shared/scale${i}`);
const mountDirs = (i: number) => [
   path.join(root, `src/routes/inventory/scale${i}`),
   path.join(root, `src/routes/finances/scale${i}`),
];

function helperFile(i: number): string {
   const ids = `"/inventory/scale${i}/thing" | "/finances/scale${i}/thing"`;
   return `/* eslint-disable */
// Generated by tsr-shared-routes. Do not edit.
import * as React from "react";
import { Link, useMatch, useNavigate, useRouter } from "@tanstack/react-router";
import type {
  AnyContext, AnyRoute, FileBaseRouteOptions, FileRoutesByPath, Register,
  ResolveParams, RouteApi, UpdatableRouteOptions, UseNavigateResult,
} from "@tanstack/react-router";

const MOUNT_IDS: ReadonlySet<string> = new Set([
  "/inventory/scale${i}/thing",
  "/finances/scale${i}/thing",
]);
type MountFilePaths = ${ids};

type EntryOf<K extends string> = K extends keyof FileRoutesByPath
  ? FileRoutesByPath[K]
  : { id: K; path: string; fullPath: K; parentRoute: AnyRoute; preLoaderRoute: never };

type MountEntry = EntryOf<MountFilePaths>;
type MountParent = MountEntry["parentRoute"];
type MountId = MountEntry["id"];
type MountPath = MountEntry["path"];
type MountFullPath = MountEntry["fullPath"];

export type SharedRouteOptions<TSearchValidator, TParams, TRouteContextFn, TBeforeLoadFn,
  TLoaderDeps extends Record<string, any>, TLoaderFn, TSSR, TMiddlewares, THandlers,
> = FileBaseRouteOptions<Register, MountParent, MountId, MountPath, TSearchValidator, TParams,
  TLoaderDeps, TLoaderFn, AnyContext, TRouteContextFn, TBeforeLoadFn, AnyContext, TSSR, TMiddlewares, THandlers
> & UpdatableRouteOptions<MountParent, MountId, MountFullPath, TParams, TSearchValidator,
  TLoaderFn, TLoaderDeps, AnyContext, TRouteContextFn, TBeforeLoadFn>;

export interface SharedRoute<TSearchValidator, TParams, TRouteContextFn, TBeforeLoadFn,
  TLoaderDeps extends Record<string, any>, TLoaderFn, TSSR, TMiddlewares, THandlers,
> {
  options: SharedRouteOptions<TSearchValidator, TParams, TRouteContextFn, TBeforeLoadFn,
    TLoaderDeps, TLoaderFn, TSSR, TMiddlewares, THandlers>;
  "~types": {
    searchValidator: TSearchValidator; params: TParams; routeContextFn: TRouteContextFn;
    beforeLoadFn: TBeforeLoadFn; loaderDeps: TLoaderDeps; loaderFn: TLoaderFn;
    ssr: TSSR; middlewares: TMiddlewares; handlers: THandlers;
  };
  useSearch: RouteApi<MountId>["useSearch"];
  useParams: RouteApi<MountId>["useParams"];
  useLoaderData: RouteApi<MountId>["useLoaderData"];
  useNavigate: () => UseNavigateResult<MountFullPath>;
  Link: RouteApi<MountId>["Link"];
}

function useMountRouteId(): string {
  const nearestRouteId = useMatch({ strict: false, select: (m) => m.routeId });
  const router = useRouter();
  let route: AnyRoute | undefined =
    nearestRouteId === undefined ? undefined : (router.routesById as any)[nearestRouteId];
  while (route && !MOUNT_IDS.has(route.id)) route = route.parentRoute;
  if (!route) throw new Error("outside mounts");
  return route.id;
}

export function createSharedRoute<
  TSearchValidator = undefined, TParams = ResolveParams<MountPath>,
  TRouteContextFn = AnyContext, TBeforeLoadFn = AnyContext,
  TLoaderDeps extends Record<string, any> = {}, TLoaderFn = undefined,
  TSSR = unknown, const TMiddlewares = unknown, THandlers = undefined,
>(
  options: SharedRouteOptions<TSearchValidator, TParams, TRouteContextFn, TBeforeLoadFn,
    TLoaderDeps, TLoaderFn, TSSR, TMiddlewares, THandlers>,
): SharedRoute<TSearchValidator, TParams, TRouteContextFn, TBeforeLoadFn,
  TLoaderDeps, TLoaderFn, TSSR, TMiddlewares, THandlers> {
  const useMountFullPath = () => {
    const id = useMountRouteId();
    const router = useRouter();
    return (router.routesById as any)[id].fullPath;
  };
  return {
    options,
    useSearch: (opts?: any) => {
      const from = useMountRouteId();
      return useMatch({ ...opts, from, select: (m: any) => (opts?.select ? opts.select(m.search) : m.search) } as any);
    },
    useParams: (opts?: any) => {
      const from = useMountRouteId();
      return useMatch({ ...opts, from, select: (m: any) => (opts?.select ? opts.select(m._strictParams) : m._strictParams) } as any);
    },
    useLoaderData: (opts?: any) => {
      const from = useMountRouteId();
      return useMatch({ ...opts, from, select: (m: any) => (opts?.select ? opts.select(m.loaderData) : m.loaderData) } as any);
    },
    useNavigate: () => useNavigate({ from: useMountFullPath() }),
    Link: React.forwardRef(function SharedLink(props: any, ref: any) {
      return <Link ref={ref} from={useMountFullPath()} {...props} />;
    }),
  } as any;
}
`;
}

function sharedFile(i: number): string {
   return `import { z } from "zod";
import { createSharedRoute } from "./thing.gen";

export const shared = createSharedRoute({
  validateSearch: z.object({
    q${i}: z.string().optional(),
    page: z.number().default(1),
  }),
  loaderDeps: ({ search }) => ({ page: search.page }),
  loader: async ({ deps }) => ({ items${i}: [deps.page, ${i}], label: "thing${i}" }),
  component: Thing${i},
});

function Thing${i}() {
  const data = shared.useLoaderData();
  const search = shared.useSearch();
  const navigate = shared.useNavigate();
  return (
    <div onClick={() => navigate({ to: ".", search: { page: (search.page ?? 0) + 1 } })}>
      {data.label} {search.q${i}} <shared.Link to=".">self</shared.Link>
    </div>
  );
}
`;
}

function wrapperFile(i: number, mount: "inventory" | "finances"): string {
   return `// Generated by tsr-shared-routes. Do not edit.
import { createFileRoute } from "@tanstack/react-router";
import type { Register } from "@tanstack/react-router";
import { shared } from "../../../shared/scale${i}/thing";

type T = (typeof shared)["~types"];

export const Route = createFileRoute("/${mount}/scale${i}/thing")<
  Register, T["searchValidator"], T["params"], T["routeContextFn"], T["beforeLoadFn"],
  T["loaderDeps"], T["loaderFn"], unknown, T["ssr"], T["middlewares"], T["handlers"]
>({ ...shared.options } as any);
`;
}

function stockFile(i: number, mount: "inventory" | "finances"): string {
   return `import { z } from "zod";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/${mount}/scale${i}/thing")({
  validateSearch: z.object({
    q${i}: z.string().optional(),
    page: z.number().default(1),
  }),
  loaderDeps: ({ search }) => ({ page: search.page }),
  loader: async ({ deps }) => ({ items${i}: [deps.page, ${i}], label: "thing${i}" }),
  component: Thing,
});

function Thing() {
  const data = Route.useLoaderData();
  const search = Route.useSearch();
  const navigate = Route.useNavigate();
  return (
    <div onClick={() => navigate({ to: ".", search: { page: (search.page ?? 0) + 1 } })}>
      {data.label} {search.q${i}} <span>self</span>
    </div>
  );
}
`;
}

function clean() {
   for (let i = 1; i <= N; i++) {
      fs.rmSync(sharedDir(i), { recursive: true, force: true });
      for (const d of mountDirs(i)) fs.rmSync(d, { recursive: true, force: true });
   }
}

if (mode === "clean") {
   clean();
   console.log("cleaned");
} else if (mode === "shared") {
   clean();
   for (let i = 1; i <= N; i++) {
      fs.mkdirSync(sharedDir(i), { recursive: true });
      fs.writeFileSync(path.join(sharedDir(i), "thing.gen.tsx"), helperFile(i));
      fs.writeFileSync(path.join(sharedDir(i), "thing.tsx"), sharedFile(i));
      const [inv, fin] = mountDirs(i);
      fs.mkdirSync(inv!, { recursive: true });
      fs.mkdirSync(fin!, { recursive: true });
      fs.writeFileSync(path.join(inv!, "thing.tsx"), wrapperFile(i, "inventory"));
      fs.writeFileSync(path.join(fin!, "thing.tsx"), wrapperFile(i, "finances"));
   }
   console.log(`shared fixture: ${N} shared files x 2 mounts`);
} else if (mode === "stock") {
   clean();
   for (let i = 1; i <= N; i++) {
      const [inv, fin] = mountDirs(i);
      fs.mkdirSync(inv!, { recursive: true });
      fs.mkdirSync(fin!, { recursive: true });
      fs.writeFileSync(path.join(inv!, "thing.tsx"), stockFile(i, "inventory"));
      fs.writeFileSync(path.join(fin!, "thing.tsx"), stockFile(i, "finances"));
   }
   console.log(`stock fixture: ${N * 2} plain route files`);
} else {
   console.error("usage: bun scripts/scale-fixture.ts shared|stock|clean");
   process.exit(1);
}
