// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-one/route.tsx
// mounts: /home/shared-one, /about/shared-one
import { makeSharedRoute } from "../../../sharedRoutes.gen";

type MountFilePaths = "/home/shared-one" | "/about/shared-one";

export const shared = makeSharedRoute<MountFilePaths>(
   ["/home/shared-one", "/about/shared-one"],
   "src/routes/home/shared-one/route",
);
