/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinancesRouteRouteImport } from './routes/finances/route'
import { Route as InventoryRouteRouteImport } from './routes/inventory/route'
import { Route as FinancesProvidersIndexRouteImport } from './routes/finances/providers/index'
import { Route as FinancesProvidersProviderIdRouteImport } from './routes/finances/providers/$providerId'
import { Route as InventoryProvidersIndexRouteImport } from './routes/inventory/providers/index'
import { Route as InventoryProvidersProviderIdRouteImport } from './routes/inventory/providers/$providerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRouteRoute = FinancesRouteRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRouteRoute = InventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesProvidersIndexRoute = FinancesProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => FinancesRouteRoute,
} as any)
const FinancesProvidersProviderIdRoute =
  FinancesProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => FinancesRouteRoute,
  } as any)
const InventoryProvidersIndexRoute = InventoryProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const InventoryProvidersProviderIdRoute =
  InventoryProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => InventoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/finances/providers/$providerId': typeof FinancesProvidersProviderIdRoute
  '/inventory/providers/$providerId': typeof InventoryProvidersProviderIdRoute
  '/finances/providers/': typeof FinancesProvidersIndexRoute
  '/inventory/providers/': typeof InventoryProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/finances/providers/$providerId': typeof FinancesProvidersProviderIdRoute
  '/inventory/providers/$providerId': typeof InventoryProvidersProviderIdRoute
  '/finances/providers': typeof FinancesProvidersIndexRoute
  '/inventory/providers': typeof InventoryProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finances': typeof FinancesRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/finances/providers/$providerId': typeof FinancesProvidersProviderIdRoute
  '/inventory/providers/$providerId': typeof InventoryProvidersProviderIdRoute
  '/finances/providers/': typeof FinancesProvidersIndexRoute
  '/inventory/providers/': typeof InventoryProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finances'
    | '/inventory'
    | '/finances/providers/$providerId'
    | '/inventory/providers/$providerId'
    | '/finances/providers/'
    | '/inventory/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finances'
    | '/inventory'
    | '/finances/providers/$providerId'
    | '/inventory/providers/$providerId'
    | '/finances/providers'
    | '/inventory/providers'
  id:
    | '__root__'
    | '/'
    | '/finances'
    | '/inventory'
    | '/finances/providers/$providerId'
    | '/inventory/providers/$providerId'
    | '/finances/providers/'
    | '/inventory/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancesRouteRoute: typeof FinancesRouteRouteWithChildren
  InventoryRouteRoute: typeof InventoryRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances/providers/': {
      id: '/finances/providers/'
      path: '/providers'
      fullPath: '/finances/providers/'
      preLoaderRoute: typeof FinancesProvidersIndexRouteImport
      parentRoute: typeof FinancesRouteRoute
    }
    '/finances/providers/$providerId': {
      id: '/finances/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/finances/providers/$providerId'
      preLoaderRoute: typeof FinancesProvidersProviderIdRouteImport
      parentRoute: typeof FinancesRouteRoute
    }
    '/inventory/providers/': {
      id: '/inventory/providers/'
      path: '/providers'
      fullPath: '/inventory/providers/'
      preLoaderRoute: typeof InventoryProvidersIndexRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/inventory/providers/$providerId': {
      id: '/inventory/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/inventory/providers/$providerId'
      preLoaderRoute: typeof InventoryProvidersProviderIdRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
  }
}

interface FinancesRouteRouteChildren {
  FinancesProvidersProviderIdRoute: typeof FinancesProvidersProviderIdRoute
  FinancesProvidersIndexRoute: typeof FinancesProvidersIndexRoute
}

const FinancesRouteRouteChildren: FinancesRouteRouteChildren = {
  FinancesProvidersProviderIdRoute: FinancesProvidersProviderIdRoute,
  FinancesProvidersIndexRoute: FinancesProvidersIndexRoute,
}

const FinancesRouteRouteWithChildren = FinancesRouteRoute._addFileChildren(
  FinancesRouteRouteChildren,
)

interface InventoryRouteRouteChildren {
  InventoryProvidersProviderIdRoute: typeof InventoryProvidersProviderIdRoute
  InventoryProvidersIndexRoute: typeof InventoryProvidersIndexRoute
}

const InventoryRouteRouteChildren: InventoryRouteRouteChildren = {
  InventoryProvidersProviderIdRoute: InventoryProvidersProviderIdRoute,
  InventoryProvidersIndexRoute: InventoryProvidersIndexRoute,
}

const InventoryRouteRouteWithChildren = InventoryRouteRoute._addFileChildren(
  InventoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancesRouteRoute: FinancesRouteRouteWithChildren,
  InventoryRouteRoute: InventoryRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
