// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/shared/providers/$providerId.tsx
// mounts: /finances/providers/$providerId, /inventory/providers/$providerId
import { makeCreateSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/finances/providers/$providerId" | "/inventory/providers/$providerId";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
   ["/finances/providers/$providerId", "/inventory/providers/$providerId"],
   "src/shared/providers/$providerId",
);
