// Generated by tanstack-shared-routes. Do not edit.
/* eslint-disable */
// source: src/shared/providers/chart.tsx
// mounts: /finances/providers/chart, /inventory/providers/chart
import { makeCreateSharedRoute } from "./__shared-routes.gen";

type MountFilePaths = "/finances/providers/chart" | "/inventory/providers/chart";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
  [
  "/finances/providers/chart",
  "/inventory/providers/chart",
  ],
  "src/shared/providers/chart",
);
