// Generated by tanstack-shared-routes. Do not edit.
/* eslint-disable */
// source: src/shared/providers/index.tsx
// mounts: /finances/providers/, /inventory/providers/
import { makeCreateSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/finances/providers/" | "/inventory/providers/";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
  [
  "/finances/providers/",
  "/inventory/providers/",
  ],
  "src/shared/providers/index",
);
