// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/guides/faq.tsx (mount: src/routes/inventory/help.mount.ts)
import type { Register } from '@tanstack/react-router'
import { createFileRoute } from '@tanstack/react-router'
import type { SourceRouteTypes } from '../../../../sharedRoutes.gen'
import { patchSharedHooks } from '../../../../sharedRoutes.gen'
import { Route as shared } from '../../../help/guides/faq'

patchSharedHooks(shared, ['/help/guides/faq', '/inventory/help/guides/faq', '/settings/guides/faq'])

type T = SourceRouteTypes<typeof shared>

const { id: _id, path: _path, getParentRoute: _getParentRoute, ...sourceOptions } = shared.options as any

export const Route = createFileRoute('/inventory/help/guides/faq')<
  Register,
  T['searchValidator'],
  T['params'],
  T['routeContextFn'],
  T['beforeLoadFn'],
  T['loaderDeps'],
  T['loaderFn'],
  unknown,
  T['ssr'],
  T['middlewares'],
  T['handlers']
>({ ...sourceOptions })
