// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/modal/open.tsx
// mounts: /modal/open, /help/modal/open, /inventory/help/modal/open
import { makeSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/modal/open" | "/help/modal/open" | "/inventory/help/modal/open";

export const shared = makeSharedRoute<MountFilePaths>(
   ["/modal/open", "/help/modal/open", "/inventory/help/modal/open"],
   "src/routes/modal/open",
);
