/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as InventoryRouteRouteImport } from './routes/inventory/route'
import { Route as RequiredSearchRouteImport } from './routes/required-search'
import { Route as HelpTopicIdRouteImport } from './routes/help/$topicId'
import { Route as HelpChartRouteImport } from './routes/help/chart'
import { Route as InventoryHelpRouteRouteImport } from './routes/inventory/help/route'
import { Route as InventoryStockRouteImport } from './routes/inventory/stock'
import { Route as ModalOpenRouteImport } from './routes/modal/open'
import { Route as HelpGuidesFaqRouteImport } from './routes/help/guides/faq'
import { Route as HelpModalOpenRouteImport } from './routes/help/modal/open'
import { Route as InventoryHelpTopicIdRouteImport } from './routes/inventory/help/$topicId'
import { Route as InventoryHelpChartRouteImport } from './routes/inventory/help/chart'
import { Route as SettingsGuidesFaqRouteImport } from './routes/settings/guides/faq'
import { Route as InventoryHelpGuidesFaqRouteImport } from './routes/inventory/help/guides/faq'
import { Route as InventoryHelpModalOpenRouteImport } from './routes/inventory/help/modal/open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRouteRoute = InventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const RequiredSearchRoute = RequiredSearchRouteImport.update({
  id: '/required-search',
  path: '/required-search',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTopicIdRoute = HelpTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => HelpRouteRoute,
} as any)
const HelpChartRoute = HelpChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => HelpRouteRoute,
} as any).lazy(() => import('./routes/help/chart.lazy').then((d) => d.Route))
const InventoryHelpRouteRoute = InventoryHelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventoryRouteRoute,
} as any)
const ModalOpenRoute = ModalOpenRouteImport.update({
  id: '/modal/open',
  path: '/modal/open',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpGuidesFaqRoute = HelpGuidesFaqRouteImport.update({
  id: '/guides/faq',
  path: '/guides/faq',
  getParentRoute: () => HelpRouteRoute,
} as any)
const HelpModalOpenRoute = HelpModalOpenRouteImport.update({
  id: '/modal/open',
  path: '/modal/open',
  getParentRoute: () => HelpRouteRoute,
} as any)
const InventoryHelpTopicIdRoute = InventoryHelpTopicIdRouteImport.update({
  id: '/$topicId',
  path: '/$topicId',
  getParentRoute: () => InventoryHelpRouteRoute,
} as any)
const InventoryHelpChartRoute = InventoryHelpChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => InventoryHelpRouteRoute,
} as any).lazy(() =>
  import('./routes/inventory/help/chart.lazy').then((d) => d.Route),
)
const SettingsGuidesFaqRoute = SettingsGuidesFaqRouteImport.update({
  id: '/settings/guides/faq',
  path: '/settings/guides/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryHelpGuidesFaqRoute = InventoryHelpGuidesFaqRouteImport.update({
  id: '/guides/faq',
  path: '/guides/faq',
  getParentRoute: () => InventoryHelpRouteRoute,
} as any)
const InventoryHelpModalOpenRoute = InventoryHelpModalOpenRouteImport.update({
  id: '/modal/open',
  path: '/modal/open',
  getParentRoute: () => InventoryHelpRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/required-search': typeof RequiredSearchRoute
  '/inventory/help': typeof InventoryHelpRouteRouteWithChildren
  '/help/$topicId': typeof HelpTopicIdRoute
  '/help/chart': typeof HelpChartRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/modal/open': typeof ModalOpenRoute
  '/help/guides/faq': typeof HelpGuidesFaqRoute
  '/help/modal/open': typeof HelpModalOpenRoute
  '/inventory/help/$topicId': typeof InventoryHelpTopicIdRoute
  '/inventory/help/chart': typeof InventoryHelpChartRoute
  '/settings/guides/faq': typeof SettingsGuidesFaqRoute
  '/inventory/help/guides/faq': typeof InventoryHelpGuidesFaqRoute
  '/inventory/help/modal/open': typeof InventoryHelpModalOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/required-search': typeof RequiredSearchRoute
  '/inventory/help': typeof InventoryHelpRouteRouteWithChildren
  '/help/$topicId': typeof HelpTopicIdRoute
  '/help/chart': typeof HelpChartRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/modal/open': typeof ModalOpenRoute
  '/help/guides/faq': typeof HelpGuidesFaqRoute
  '/help/modal/open': typeof HelpModalOpenRoute
  '/inventory/help/$topicId': typeof InventoryHelpTopicIdRoute
  '/inventory/help/chart': typeof InventoryHelpChartRoute
  '/settings/guides/faq': typeof SettingsGuidesFaqRoute
  '/inventory/help/guides/faq': typeof InventoryHelpGuidesFaqRoute
  '/inventory/help/modal/open': typeof InventoryHelpModalOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/inventory': typeof InventoryRouteRouteWithChildren
  '/required-search': typeof RequiredSearchRoute
  '/inventory/help': typeof InventoryHelpRouteRouteWithChildren
  '/help/$topicId': typeof HelpTopicIdRoute
  '/help/chart': typeof HelpChartRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/modal/open': typeof ModalOpenRoute
  '/help/guides/faq': typeof HelpGuidesFaqRoute
  '/help/modal/open': typeof HelpModalOpenRoute
  '/inventory/help/$topicId': typeof InventoryHelpTopicIdRoute
  '/inventory/help/chart': typeof InventoryHelpChartRoute
  '/settings/guides/faq': typeof SettingsGuidesFaqRoute
  '/inventory/help/guides/faq': typeof InventoryHelpGuidesFaqRoute
  '/inventory/help/modal/open': typeof InventoryHelpModalOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/inventory'
    | '/required-search'
    | '/inventory/help'
    | '/help/$topicId'
    | '/help/chart'
    | '/inventory/stock'
    | '/modal/open'
    | '/help/guides/faq'
    | '/help/modal/open'
    | '/inventory/help/$topicId'
    | '/inventory/help/chart'
    | '/settings/guides/faq'
    | '/inventory/help/guides/faq'
    | '/inventory/help/modal/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/inventory'
    | '/required-search'
    | '/inventory/help'
    | '/help/$topicId'
    | '/help/chart'
    | '/inventory/stock'
    | '/modal/open'
    | '/help/guides/faq'
    | '/help/modal/open'
    | '/inventory/help/$topicId'
    | '/inventory/help/chart'
    | '/settings/guides/faq'
    | '/inventory/help/guides/faq'
    | '/inventory/help/modal/open'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/inventory'
    | '/required-search'
    | '/inventory/help'
    | '/help/$topicId'
    | '/help/chart'
    | '/inventory/stock'
    | '/modal/open'
    | '/help/guides/faq'
    | '/help/modal/open'
    | '/inventory/help/$topicId'
    | '/inventory/help/chart'
    | '/settings/guides/faq'
    | '/inventory/help/guides/faq'
    | '/inventory/help/modal/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRouteRoute: typeof HelpRouteRouteWithChildren
  InventoryRouteRoute: typeof InventoryRouteRouteWithChildren
  RequiredSearchRoute: typeof RequiredSearchRoute
  ModalOpenRoute: typeof ModalOpenRoute
  SettingsGuidesFaqRoute: typeof SettingsGuidesFaqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/required-search': {
      id: '/required-search'
      path: '/required-search'
      fullPath: '/required-search'
      preLoaderRoute: typeof RequiredSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$topicId': {
      id: '/help/$topicId'
      path: '/$topicId'
      fullPath: '/help/$topicId'
      preLoaderRoute: typeof HelpTopicIdRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/help/chart': {
      id: '/help/chart'
      path: '/chart'
      fullPath: '/help/chart'
      preLoaderRoute: typeof HelpChartRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/inventory/help': {
      id: '/inventory/help'
      path: '/help'
      fullPath: '/inventory/help'
      preLoaderRoute: typeof InventoryHelpRouteRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof InventoryRouteRoute
    }
    '/modal/open': {
      id: '/modal/open'
      path: '/modal/open'
      fullPath: '/modal/open'
      preLoaderRoute: typeof ModalOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/guides/faq': {
      id: '/help/guides/faq'
      path: '/guides/faq'
      fullPath: '/help/guides/faq'
      preLoaderRoute: typeof HelpGuidesFaqRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/help/modal/open': {
      id: '/help/modal/open'
      path: '/modal/open'
      fullPath: '/help/modal/open'
      preLoaderRoute: typeof HelpModalOpenRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/inventory/help/$topicId': {
      id: '/inventory/help/$topicId'
      path: '/$topicId'
      fullPath: '/inventory/help/$topicId'
      preLoaderRoute: typeof InventoryHelpTopicIdRouteImport
      parentRoute: typeof InventoryHelpRouteRoute
    }
    '/inventory/help/chart': {
      id: '/inventory/help/chart'
      path: '/chart'
      fullPath: '/inventory/help/chart'
      preLoaderRoute: typeof InventoryHelpChartRouteImport
      parentRoute: typeof InventoryHelpRouteRoute
    }
    '/settings/guides/faq': {
      id: '/settings/guides/faq'
      path: '/settings/guides/faq'
      fullPath: '/settings/guides/faq'
      preLoaderRoute: typeof SettingsGuidesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/help/guides/faq': {
      id: '/inventory/help/guides/faq'
      path: '/guides/faq'
      fullPath: '/inventory/help/guides/faq'
      preLoaderRoute: typeof InventoryHelpGuidesFaqRouteImport
      parentRoute: typeof InventoryHelpRouteRoute
    }
    '/inventory/help/modal/open': {
      id: '/inventory/help/modal/open'
      path: '/modal/open'
      fullPath: '/inventory/help/modal/open'
      preLoaderRoute: typeof InventoryHelpModalOpenRouteImport
      parentRoute: typeof InventoryHelpRouteRoute
    }
  }
}

interface HelpRouteRouteChildren {
  HelpTopicIdRoute: typeof HelpTopicIdRoute
  HelpChartRoute: typeof HelpChartRoute
  HelpGuidesFaqRoute: typeof HelpGuidesFaqRoute
  HelpModalOpenRoute: typeof HelpModalOpenRoute
}

const HelpRouteRouteChildren: HelpRouteRouteChildren = {
  HelpTopicIdRoute: HelpTopicIdRoute,
  HelpChartRoute: HelpChartRoute,
  HelpGuidesFaqRoute: HelpGuidesFaqRoute,
  HelpModalOpenRoute: HelpModalOpenRoute,
}

const HelpRouteRouteWithChildren = HelpRouteRoute._addFileChildren(
  HelpRouteRouteChildren,
)

interface InventoryHelpRouteRouteChildren {
  InventoryHelpTopicIdRoute: typeof InventoryHelpTopicIdRoute
  InventoryHelpChartRoute: typeof InventoryHelpChartRoute
  InventoryHelpGuidesFaqRoute: typeof InventoryHelpGuidesFaqRoute
  InventoryHelpModalOpenRoute: typeof InventoryHelpModalOpenRoute
}

const InventoryHelpRouteRouteChildren: InventoryHelpRouteRouteChildren = {
  InventoryHelpTopicIdRoute: InventoryHelpTopicIdRoute,
  InventoryHelpChartRoute: InventoryHelpChartRoute,
  InventoryHelpGuidesFaqRoute: InventoryHelpGuidesFaqRoute,
  InventoryHelpModalOpenRoute: InventoryHelpModalOpenRoute,
}

const InventoryHelpRouteRouteWithChildren =
  InventoryHelpRouteRoute._addFileChildren(InventoryHelpRouteRouteChildren)

interface InventoryRouteRouteChildren {
  InventoryHelpRouteRoute: typeof InventoryHelpRouteRouteWithChildren
  InventoryStockRoute: typeof InventoryStockRoute
}

const InventoryRouteRouteChildren: InventoryRouteRouteChildren = {
  InventoryHelpRouteRoute: InventoryHelpRouteRouteWithChildren,
  InventoryStockRoute: InventoryStockRoute,
}

const InventoryRouteRouteWithChildren = InventoryRouteRoute._addFileChildren(
  InventoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRouteRoute: HelpRouteRouteWithChildren,
  InventoryRouteRoute: InventoryRouteRouteWithChildren,
  RequiredSearchRoute: RequiredSearchRoute,
  ModalOpenRoute: ModalOpenRoute,
  SettingsGuidesFaqRoute: SettingsGuidesFaqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
