// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/-shared-one/$sharedOneChild/route.tsx
// mounts: /about/$sharedOneChild, /about/shared-one/$sharedOneChild, /home/$sharedOneChild, /home/shared-one/$sharedOneChild
import { makeCreateSharedRoute } from "../../../sharedRoutes.gen";

type MountFilePaths =
   | "/about/$sharedOneChild"
   | "/about/shared-one/$sharedOneChild"
   | "/home/$sharedOneChild"
   | "/home/shared-one/$sharedOneChild";

export const createSharedRoute = makeCreateSharedRoute<MountFilePaths>(
   [
      "/about/$sharedOneChild",
      "/about/shared-one/$sharedOneChild",
      "/home/$sharedOneChild",
      "/home/shared-one/$sharedOneChild",
   ],
   "src/routes/-shared-one/$sharedOneChild/route",
);
