import path from "node:path";
import type { SharedRoutesConfig } from "../config";
import { discoverMounts } from "./discover";
import { decideWrite, renderWrapper } from "./emit-wrapper";
import { SharedRoutesError } from "./errors";
import { atomicWrite, isOwned, maskedHash, readIfExists } from "./fsio";
import { updateGitignore } from "./gitignore";
import type { ManifestFileEntry } from "./manifest";
import { cleanupStale, readManifest, writeManifest } from "./manifest";
import { buildPlan } from "./plan";
import { computeRouteIdLiteral } from "./route-id";

export interface PipelineSummary {
  /** Root-relative posix paths written (or that would be written in check mode). */
  written: Array<string>;
  /** Files whose on-disk literal was adopted (generator authority) — nothing written. */
  adopted: Array<string>;
  /** Stale generated files deleted (or that would be deleted in check mode). */
  deleted: Array<string>;
  /** Desired files already byte-identical on disk. */
  unchanged: number;
  /** Non-fatal problems (hard failures throw SharedRoutesError instead). */
  errors: Array<string>;
}

export interface PipelineOptions {
  /** Report what WOULD change without writing anything (CLI --check). */
  check?: boolean;
}

/**
 * Full codegen pass: discover mounts → scan shared dirs → plan → compute
 * route-id literals → render wrappers → diff/adopt → atomic writes → stale
 * cleanup → manifest → gitignore. All validation errors are raised before the
 * first filesystem mutation. No Vite coupling lives here.
 */
export function runPipeline(
  config: SharedRoutesConfig,
  options: PipelineOptions = {},
): PipelineSummary {
  const check = options.check ?? false;
  const root = config.root;
  const routesDir = path.resolve(root, config.routesDirectory);
  const manifestPath = path.resolve(root, config.manifestPath);
  const rel = (p: string): string => path.relative(root, p).split(path.sep).join("/");

  // 1-2. Discover + plan (read-only; throws on any invalid configuration).
  const mounts = discoverMounts(routesDir);
  const plan = buildPlan(config, mounts);

  // 3. Compute literals and render desired content.
  const desired = plan.files.map((file) => {
    const wrapperRelPath = path.relative(routesDir, file.targetPath).split(path.sep).join("/");
    const routeIdLiteral = computeRouteIdLiteral(wrapperRelPath, {
      indexToken: config.indexToken,
      routeToken: config.routeToken,
    });
    const content = renderWrapper({
      kind: file.kind,
      routeIdLiteral,
      targetPath: file.targetPath,
      sharedFilePath: file.sharedFilePath,
      sourceLabel: rel(file.sharedFilePath),
      mountLabel: rel(file.mountFilePath),
      target: config.target,
      banner: config.banner,
    });
    return { file, content };
  });

  // 4. Ownership pre-check on EVERY target before any write happens.
  const existingByPath = new Map<string, string | undefined>();
  for (const { file } of desired) {
    const existing = readIfExists(file.targetPath);
    if (existing !== undefined && !isOwned(existing)) {
      throw new SharedRoutesError(
        "UNOWNED_TARGET_FILE",
        `refusing to overwrite ${rel(file.targetPath)}\nThis file exists but was not generated by tanstack-shared-routes.\n→ Remove the file, or remove/rename the mount ${rel(file.mountFilePath)}.`,
      );
    }
    existingByPath.set(file.targetPath, existing);
  }

  // 5. Diff, adopt generator-corrected literals, write atomically.
  const written: Array<string> = [];
  const adopted: Array<string> = [];
  let unchanged = 0;
  const finalContent = new Map<string, string>();
  for (const { file, content } of desired) {
    const decision = decideWrite(existingByPath.get(file.targetPath), content);
    finalContent.set(file.targetPath, decision.content);
    if (decision.action === "write") {
      if (!check) atomicWrite(file.targetPath, decision.content);
      written.push(rel(file.targetPath));
    } else if (decision.action === "adopt") {
      adopted.push(rel(file.targetPath));
    } else {
      unchanged++;
    }
  }

  // 6. Stale cleanup (manifest ∪ banner scan, banner re-confirmed at unlink).
  const previousManifest = readManifest(manifestPath);
  const desiredPaths = new Set(desired.map(({ file }) => file.targetPath));
  const { deleted } = cleanupStale({
    root,
    manifest: previousManifest,
    currentTargetDirs: plan.targetDirs,
    desiredPaths,
    dryRun: check,
  });

  // 7. New manifest: desired files + every directory we own.
  if (!check) {
    const isWithin = (parent: string, child: string): boolean => {
      const relPath = path.relative(parent, child);
      return relPath === "" || (!relPath.startsWith("..") && !path.isAbsolute(relPath));
    };
    const dirSet = new Set<string>(plan.targetDirs);
    for (const { file } of desired) {
      let dir = path.dirname(file.targetPath);
      while (plan.targetDirs.some((targetDir) => isWithin(targetDir, dir)) && !dirSet.has(dir)) {
        dirSet.add(dir);
        dir = path.dirname(dir);
      }
    }
    const files: Array<ManifestFileEntry> = desired.map(({ file }) => ({
      path: rel(file.targetPath),
      role: "wrapper",
      mount: rel(file.mountFilePath),
      source: rel(file.sharedFilePath),
      hash: maskedHash(finalContent.get(file.targetPath)!),
    }));
    writeManifest(manifestPath, {
      version: 1,
      files,
      dirs: [...dirSet].map(rel).sort(),
    });
  }

  // 8. Managed .gitignore block (removed when the option is off).
  updateGitignore({
    gitignorePath: path.join(root, ".gitignore"),
    enabled: config.gitignore,
    entries: [
      ...plan.targetDirs.map((dir) => `${rel(dir)}/`),
      ...plan.sharedRoots.map((dir) => `${rel(dir)}/**/*.gen.*`),
    ],
    dryRun: check,
  });

  written.sort();
  adopted.sort();
  return {
    written,
    adopted,
    deleted: deleted.map(rel).sort(),
    unchanged,
    errors: plan.warnings,
  };
}

/** Check mode for CI drift guards: returns what WOULD change, writes nothing. */
export function checkPipeline(config: SharedRoutesConfig): PipelineSummary {
  return runPipeline(config, { check: true });
}
