// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/chart.tsx (mount: src/routes/inventory/help.mount.ts)
import type { Register } from '@tanstack/react-router'
import { createFileRoute } from '@tanstack/react-router'
import type { SourceRouteTypes } from '../../../sharedRoutes.gen'
import { patchSharedHooks } from '../../../sharedRoutes.gen'
import { Route as shared } from '../../help/chart'

patchSharedHooks(shared, ['/help/chart', '/inventory/help/chart'])

type T = SourceRouteTypes<typeof shared>

export const Route = createFileRoute('/inventory/help/chart')<
  Register,
  T['searchValidator'],
  T['params'],
  T['routeContextFn'],
  T['beforeLoadFn'],
  T['loaderDeps'],
  T['loaderFn'],
  unknown,
  T['ssr'],
  T['middlewares'],
  T['handlers']
>({ ...shared.options } as any)
