// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/chart.lazy.tsx (mount: src/routes/inventory/help.mount.ts)
import { createLazyFileRoute } from "@tanstack/react-router";
import { patchSharedHooks } from "../../../sharedRoutes.gen";
import { Route as sharedLazy } from "../../help/chart.lazy";

patchSharedHooks(sharedLazy, ["/help/chart", "/inventory/help/chart"]);

const { id: _id, ...lazyOptions } = sharedLazy.options;

export const Route = createLazyFileRoute("/inventory/help/chart")({ ...lazyOptions });
