// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/-shared-one/$sharedOneChild/route.tsx (mount: src/routes/home/shared-one.mount.ts)
import type { Register } from "@tanstack/react-router";
import { createFileRoute } from "@tanstack/react-router";
import { shared } from "../../../-shared-one/$sharedOneChild/route";

type T = (typeof shared)["~types"];

export const Route = createFileRoute("/home/shared-one/$sharedOneChild")<
   Register,
   T["searchValidator"],
   T["params"],
   T["routeContextFn"],
   T["beforeLoadFn"],
   T["loaderDeps"],
   T["loaderFn"],
   unknown,
   T["ssr"],
   T["middlewares"],
   T["handlers"]
>({ ...shared.options } as any);
