// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/home/shared-one/$sharedOneChild/route.tsx
// mounts: /home/shared-one/$sharedOneChild, /about/$sharedOneChild, /about/shared-one/$sharedOneChild, /home/$sharedOneChild
import { makeSharedRoute } from "../../../../sharedRoutes.gen";

type MountFilePaths =
   | "/home/shared-one/$sharedOneChild"
   | "/about/$sharedOneChild"
   | "/about/shared-one/$sharedOneChild"
   | "/home/$sharedOneChild";

export const shared = makeSharedRoute<MountFilePaths>(
   [
      "/home/shared-one/$sharedOneChild",
      "/about/$sharedOneChild",
      "/about/shared-one/$sharedOneChild",
      "/home/$sharedOneChild",
   ],
   "src/routes/home/shared-one/$sharedOneChild/route",
);
