// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/$topicId.tsx
// mounts: /help/$topicId, /inventory/help/$topicId
import { makeSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/help/$topicId" | "/inventory/help/$topicId";

export const shared = makeSharedRoute<MountFilePaths>(
  [
  "/help/$topicId",
  "/inventory/help/$topicId",
  ],
  "src/routes/help/$topicId",
);
