// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/chart.tsx
// mounts: /help/chart, /inventory/help/chart
import { makeSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/help/chart" | "/inventory/help/chart";

export const shared = makeSharedRoute<MountFilePaths>(
   ["/help/chart", "/inventory/help/chart"],
   "src/routes/help/chart",
);
