// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/route.tsx
// mounts: /help, /inventory/help
import { makeSharedRoute } from "../../sharedRoutes.gen";

type MountFilePaths = "/help" | "/inventory/help";

export const shared = makeSharedRoute<MountFilePaths>(
  [
  "/help",
  "/inventory/help",
  ],
  "src/routes/help/route",
);
