// Generated by tanstack-shared-routes. Do not edit.
/* eslint-disable */
// source: src/shared/providers/chart.lazy.tsx (mount: src/routes/finances/providers.mount.ts)
import { createLazyFileRoute } from '@tanstack/react-router'
import { sharedLazy } from '../../../shared/providers/chart.lazy'

export const Route = createLazyFileRoute('/finances/providers/chart')(sharedLazy)
