/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as AboutSharedOneChildRouteRouteImport } from './routes/about/$sharedOneChild/route'
import { Route as AboutSharedOneRouteRouteImport } from './routes/about/shared-one/route'
import { Route as AboutSharedTwoRouteRouteImport } from './routes/about/shared-two/route'
import { Route as HomeSharedOneChildRouteRouteImport } from './routes/home/$sharedOneChild/route'
import { Route as HomeSharedOneRouteRouteImport } from './routes/home/shared-one/route'
import { Route as HomeSharedTwoRouteRouteImport } from './routes/home/shared-two/route'
import { Route as AboutSharedOneSharedOneChildRouteRouteImport } from './routes/about/shared-one/$sharedOneChild/route'
import { Route as HomeSharedOneSharedOneChildRouteRouteImport } from './routes/home/shared-one/$sharedOneChild/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutSharedOneChildRouteRoute =
  AboutSharedOneChildRouteRouteImport.update({
    id: '/$sharedOneChild',
    path: '/$sharedOneChild',
    getParentRoute: () => AboutRouteRoute,
  } as any)
const AboutSharedOneRouteRoute = AboutSharedOneRouteRouteImport.update({
  id: '/shared-one',
  path: '/shared-one',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutSharedTwoRouteRoute = AboutSharedTwoRouteRouteImport.update({
  id: '/shared-two',
  path: '/shared-two',
  getParentRoute: () => AboutRouteRoute,
} as any)
const HomeSharedOneChildRouteRoute = HomeSharedOneChildRouteRouteImport.update({
  id: '/$sharedOneChild',
  path: '/$sharedOneChild',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSharedOneRouteRoute = HomeSharedOneRouteRouteImport.update({
  id: '/shared-one',
  path: '/shared-one',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeSharedTwoRouteRoute = HomeSharedTwoRouteRouteImport.update({
  id: '/shared-two',
  path: '/shared-two',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AboutSharedOneSharedOneChildRouteRoute =
  AboutSharedOneSharedOneChildRouteRouteImport.update({
    id: '/$sharedOneChild',
    path: '/$sharedOneChild',
    getParentRoute: () => AboutSharedOneRouteRoute,
  } as any)
const HomeSharedOneSharedOneChildRouteRoute =
  HomeSharedOneSharedOneChildRouteRouteImport.update({
    id: '/$sharedOneChild',
    path: '/$sharedOneChild',
    getParentRoute: () => HomeSharedOneRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/about/$sharedOneChild': typeof AboutSharedOneChildRouteRoute
  '/about/shared-one': typeof AboutSharedOneRouteRouteWithChildren
  '/about/shared-two': typeof AboutSharedTwoRouteRoute
  '/home/$sharedOneChild': typeof HomeSharedOneChildRouteRoute
  '/home/shared-one': typeof HomeSharedOneRouteRouteWithChildren
  '/home/shared-two': typeof HomeSharedTwoRouteRoute
  '/about/shared-one/$sharedOneChild': typeof AboutSharedOneSharedOneChildRouteRoute
  '/home/shared-one/$sharedOneChild': typeof HomeSharedOneSharedOneChildRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/about/$sharedOneChild': typeof AboutSharedOneChildRouteRoute
  '/about/shared-one': typeof AboutSharedOneRouteRouteWithChildren
  '/about/shared-two': typeof AboutSharedTwoRouteRoute
  '/home/$sharedOneChild': typeof HomeSharedOneChildRouteRoute
  '/home/shared-one': typeof HomeSharedOneRouteRouteWithChildren
  '/home/shared-two': typeof HomeSharedTwoRouteRoute
  '/about/shared-one/$sharedOneChild': typeof AboutSharedOneSharedOneChildRouteRoute
  '/home/shared-one/$sharedOneChild': typeof HomeSharedOneSharedOneChildRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRouteWithChildren
  '/home': typeof HomeRouteRouteWithChildren
  '/about/$sharedOneChild': typeof AboutSharedOneChildRouteRoute
  '/about/shared-one': typeof AboutSharedOneRouteRouteWithChildren
  '/about/shared-two': typeof AboutSharedTwoRouteRoute
  '/home/$sharedOneChild': typeof HomeSharedOneChildRouteRoute
  '/home/shared-one': typeof HomeSharedOneRouteRouteWithChildren
  '/home/shared-two': typeof HomeSharedTwoRouteRoute
  '/about/shared-one/$sharedOneChild': typeof AboutSharedOneSharedOneChildRouteRoute
  '/home/shared-one/$sharedOneChild': typeof HomeSharedOneSharedOneChildRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/about/$sharedOneChild'
    | '/about/shared-one'
    | '/about/shared-two'
    | '/home/$sharedOneChild'
    | '/home/shared-one'
    | '/home/shared-two'
    | '/about/shared-one/$sharedOneChild'
    | '/home/shared-one/$sharedOneChild'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/about/$sharedOneChild'
    | '/about/shared-one'
    | '/about/shared-two'
    | '/home/$sharedOneChild'
    | '/home/shared-one'
    | '/home/shared-two'
    | '/about/shared-one/$sharedOneChild'
    | '/home/shared-one/$sharedOneChild'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/home'
    | '/about/$sharedOneChild'
    | '/about/shared-one'
    | '/about/shared-two'
    | '/home/$sharedOneChild'
    | '/home/shared-one'
    | '/home/shared-two'
    | '/about/shared-one/$sharedOneChild'
    | '/home/shared-one/$sharedOneChild'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/$sharedOneChild': {
      id: '/about/$sharedOneChild'
      path: '/$sharedOneChild'
      fullPath: '/about/$sharedOneChild'
      preLoaderRoute: typeof AboutSharedOneChildRouteRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/shared-one': {
      id: '/about/shared-one'
      path: '/shared-one'
      fullPath: '/about/shared-one'
      preLoaderRoute: typeof AboutSharedOneRouteRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/shared-two': {
      id: '/about/shared-two'
      path: '/shared-two'
      fullPath: '/about/shared-two'
      preLoaderRoute: typeof AboutSharedTwoRouteRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/home/$sharedOneChild': {
      id: '/home/$sharedOneChild'
      path: '/$sharedOneChild'
      fullPath: '/home/$sharedOneChild'
      preLoaderRoute: typeof HomeSharedOneChildRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/shared-one': {
      id: '/home/shared-one'
      path: '/shared-one'
      fullPath: '/home/shared-one'
      preLoaderRoute: typeof HomeSharedOneRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/shared-two': {
      id: '/home/shared-two'
      path: '/shared-two'
      fullPath: '/home/shared-two'
      preLoaderRoute: typeof HomeSharedTwoRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/about/shared-one/$sharedOneChild': {
      id: '/about/shared-one/$sharedOneChild'
      path: '/$sharedOneChild'
      fullPath: '/about/shared-one/$sharedOneChild'
      preLoaderRoute: typeof AboutSharedOneSharedOneChildRouteRouteImport
      parentRoute: typeof AboutSharedOneRouteRoute
    }
    '/home/shared-one/$sharedOneChild': {
      id: '/home/shared-one/$sharedOneChild'
      path: '/$sharedOneChild'
      fullPath: '/home/shared-one/$sharedOneChild'
      preLoaderRoute: typeof HomeSharedOneSharedOneChildRouteRouteImport
      parentRoute: typeof HomeSharedOneRouteRoute
    }
  }
}

interface AboutSharedOneRouteRouteChildren {
  AboutSharedOneSharedOneChildRouteRoute: typeof AboutSharedOneSharedOneChildRouteRoute
}

const AboutSharedOneRouteRouteChildren: AboutSharedOneRouteRouteChildren = {
  AboutSharedOneSharedOneChildRouteRoute:
    AboutSharedOneSharedOneChildRouteRoute,
}

const AboutSharedOneRouteRouteWithChildren =
  AboutSharedOneRouteRoute._addFileChildren(AboutSharedOneRouteRouteChildren)

interface AboutRouteRouteChildren {
  AboutSharedOneChildRouteRoute: typeof AboutSharedOneChildRouteRoute
  AboutSharedOneRouteRoute: typeof AboutSharedOneRouteRouteWithChildren
  AboutSharedTwoRouteRoute: typeof AboutSharedTwoRouteRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutSharedOneChildRouteRoute: AboutSharedOneChildRouteRoute,
  AboutSharedOneRouteRoute: AboutSharedOneRouteRouteWithChildren,
  AboutSharedTwoRouteRoute: AboutSharedTwoRouteRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface HomeSharedOneRouteRouteChildren {
  HomeSharedOneSharedOneChildRouteRoute: typeof HomeSharedOneSharedOneChildRouteRoute
}

const HomeSharedOneRouteRouteChildren: HomeSharedOneRouteRouteChildren = {
  HomeSharedOneSharedOneChildRouteRoute: HomeSharedOneSharedOneChildRouteRoute,
}

const HomeSharedOneRouteRouteWithChildren =
  HomeSharedOneRouteRoute._addFileChildren(HomeSharedOneRouteRouteChildren)

interface HomeRouteRouteChildren {
  HomeSharedOneChildRouteRoute: typeof HomeSharedOneChildRouteRoute
  HomeSharedOneRouteRoute: typeof HomeSharedOneRouteRouteWithChildren
  HomeSharedTwoRouteRoute: typeof HomeSharedTwoRouteRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeSharedOneChildRouteRoute: HomeSharedOneChildRouteRoute,
  HomeSharedOneRouteRoute: HomeSharedOneRouteRouteWithChildren,
  HomeSharedTwoRouteRoute: HomeSharedTwoRouteRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
