// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// The shared-route machinery used by every wrapper and .gen sibling.
// Generated into your project (not imported from the package) so its types
// resolve YOUR @tanstack/react-router instance — the one routeTree.gen.ts
// augments. See the package README ("What are the .gen files?").
import type {
   AnyRoute,
   FileRoutesByPath,
   RouteApi,
   UseNavigateResult,
} from "@tanstack/react-router";
import { Link, useMatch, useNavigate, useRouter } from "@tanstack/react-router";
import type { Route as RouteCore } from "@tanstack/router-core";
import * as React from "react";

/**
 * The shared-route machinery for mounting already-mounted routes. Source
 * files are plain stock route files (`createFileRoute`); for every source
 * file mounted elsewhere the codegen emits:
 *
 * - a wrapper per extra mount, which calls {@link patchSharedHooks} on the
 *   source `Route` so stock `Route.useX()` call sites resolve the mount they
 *   actually render under, and re-registers the source options at the mount's
 *   route id with the generics extracted via {@link SourceRouteTypes};
 * - a `.gen.tsx` sibling exporting {@link makeSharedRoute}'s union-typed view
 *   for call sites that want cross-mount honest types (relative navigation
 *   escaping the subtree, inherited search/params).
 */

// Graceful degradation: resolves per-key, falls back before the wrappers /
// routeTree.gen.ts exist so helpers never hard-error during authoring.
type EntryOf<K extends string> = K extends keyof FileRoutesByPath
   ? FileRoutesByPath[K]
   : {
        id: K;
        path: string;
        fullPath: K;
        parentRoute: AnyRoute;
        preLoaderRoute: never;
     };

type MountEntry<TMountPaths extends string> = EntryOf<TMountPaths>;
type MountId<TMountPaths extends string> = MountEntry<TMountPaths>["id"];
type MountFullPath<TMountPaths extends string> = MountEntry<TMountPaths>["fullPath"];

/**
 * Input-level generics of a stock route file's `Route` export, extracted for
 * wrapper emission. Matching is nominal against `@tanstack/router-core`'s
 * `Route` interface (the type `createFileRoute(...)(...)` returns) — several
 * generics are not recoverable from `Route['types']` members because they
 * only appear there in resolved form (e.g. `ResolveLoaderData<TLoaderFn>`),
 * hence the positional infer. Requires the app to resolve the same
 * `@tanstack/router-core` copy as `@tanstack/react-router` does (it is a
 * peer dependency of tsr-shared-routes for exactly this reason); a duplicated
 * copy degrades this type to `never`, which fails the typecheck loudly.
 */
export type SourceRouteTypes<TRoute> =
   TRoute extends RouteCore<
      infer _TRegister,
      infer _TParentRoute,
      infer _TPath,
      infer _TFullPath,
      infer _TCustomId,
      infer _TId,
      infer TSearchValidator,
      infer TParams,
      infer _TRouterContext,
      infer TRouteContextFn,
      infer TBeforeLoadFn,
      infer TLoaderDeps,
      infer TLoaderFn,
      infer _TChildren,
      infer _TFileRouteTypes,
      infer TSSR,
      infer TServerMiddlewares,
      infer THandlers
   >
      ? {
           searchValidator: TSearchValidator;
           params: TParams;
           routeContextFn: TRouteContextFn;
           beforeLoadFn: TBeforeLoadFn;
           loaderDeps: TLoaderDeps;
           loaderFn: TLoaderFn;
           ssr: TSSR;
           middlewares: TServerMiddlewares;
           handlers: THandlers;
        }
      : never;

/**
 * Union-typed view over one source file's mounts: every hook is typed
 * against the union of the file's route ids (home mount included) and
 * resolves the actual mount at runtime, so one component behaves correctly
 * under whichever mount rendered it. Exported by the generated `.gen.tsx`
 * sibling of each mounted source file.
 */
export interface SharedRoute<TMountPaths extends string> {
   useMatch: RouteApi<MountId<TMountPaths>>["useMatch"];
   useRouteContext: RouteApi<MountId<TMountPaths>>["useRouteContext"];
   useSearch: RouteApi<MountId<TMountPaths>>["useSearch"];
   useParams: RouteApi<MountId<TMountPaths>>["useParams"];
   useLoaderDeps: RouteApi<MountId<TMountPaths>>["useLoaderDeps"];
   useLoaderData: RouteApi<MountId<TMountPaths>>["useLoaderData"];
   useNavigate: () => UseNavigateResult<MountFullPath<TMountPaths>>;
   Link: RouteApi<MountId<TMountPaths>>["Link"];
}

const HOOK_KEYS = [
   "useMatch",
   "useRouteContext",
   "useSearch",
   "useParams",
   "useLoaderDeps",
   "useLoaderData",
   "useNavigate",
] as const;

/**
 * The mount-resolving hook implementations. Hooks resolve which mount the
 * component is currently rendered under — nearest match, then a static walk
 * up the route tree to the closest ancestor whose id is a mount id — so they
 * also work in components rendered by descendant routes of the mount root.
 */
function makeHooks(mountIds: ReadonlyArray<string>, label: string): Record<string, unknown> {
   const MOUNT_IDS: ReadonlySet<string> = new Set(mountIds);

   const useMountRouteId = (): string => {
      const nearestRouteId = useMatch({
         strict: false,
         select: (m) => m.routeId,
      });
      const router = useRouter();
      let route: AnyRoute | undefined =
         nearestRouteId === undefined ? undefined : (router.routesById as any)[nearestRouteId];
      while (route && !MOUNT_IDS.has(route.id)) route = route.parentRoute;
      if (!route) {
         throw new Error(
            `tsr-shared-routes: hooks of ${label} must be used under one of its mounts: ` +
               [...MOUNT_IDS].join(", "),
         );
      }
      return route.id;
   };

   const useMountFullPath = (): string => {
      const id = useMountRouteId();
      const router = useRouter();
      return (router.routesById as any)[id].fullPath;
   };

   return {
      useMatch: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({ ...opts, from } as any);
      },
      useRouteContext: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({
            from,
            select: (m: any) => (opts?.select ? opts.select(m.context) : m.context),
         } as any);
      },
      useSearch: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({
            ...opts,
            from,
            select: (m: any) => (opts?.select ? opts.select(m.search) : m.search),
         } as any);
      },
      useParams: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({
            ...opts,
            from,
            select: (m: any) => (opts?.select ? opts.select(m._strictParams) : m._strictParams),
         } as any);
      },
      useLoaderDeps: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({
            ...opts,
            from,
            select: (m: any) => (opts?.select ? opts.select(m.loaderDeps) : m.loaderDeps),
         } as any);
      },
      useLoaderData: (opts?: any) => {
         const from = useMountRouteId();
         return useMatch({
            ...opts,
            from,
            select: (m: any) => (opts?.select ? opts.select(m.loaderData) : m.loaderData),
         } as any);
      },
      useNavigate: () => {
         const fullPath = useMountFullPath();
         // `from` is a live mount path; the registered router's literal union
         // for it only exists in user-land compilations.
         return useNavigate({ from: fullPath as any });
      },
      Link: React.forwardRef(function SharedLink(props: any, ref: any) {
         const fullPath = useMountFullPath();
         return React.createElement(Link, { ref, from: fullPath, ...props });
      }),
   };
}

/**
 * Builds the union-typed view for one source file. `mountIds` are the file's
 * route ids under every mount, the home mount included. `sourcePath` names
 * the file in error messages. Needs nothing from the source module — the
 * hooks resolve via the router's live match tree — so `.gen.tsx` siblings
 * have no runtime dependency on their source file.
 */
export function makeSharedRoute<TMountPaths extends string>(
   mountIds: ReadonlyArray<string>,
   sourcePath?: string,
): SharedRoute<TMountPaths> {
   const label = sourcePath === undefined ? "this shared route file" : JSON.stringify(sourcePath);
   return makeHooks(mountIds, label) as unknown as SharedRoute<TMountPaths>;
}

const PATCHED = Symbol.for("tsr-shared-routes.patched");

/**
 * Replaces a source route instance's home-bound hooks with the
 * mount-resolving versions (and attaches a mount-resolving `Link` at
 * runtime). Called by every generated wrapper — idempotent, and since
 * `routeTree.gen.ts` imports all wrappers eagerly, the patch lands before
 * anything renders. Stock `Route.useX()` call sites keep their home-mount
 * types but become runtime-correct under every mount. Accepts both `Route`
 * and `LazyRoute` instances (both bind their hooks as assignable own
 * properties in @tanstack/react-router's constructors — the version coupling
 * this function relies on).
 */
export function patchSharedHooks(route: object, mountIds: ReadonlyArray<string>): void {
   const target = route as any;
   if (target[PATCHED]) return;
   target[PATCHED] = true;
   const hooks = makeHooks(mountIds, JSON.stringify(mountIds[0] ?? "?"));
   for (const key of HOOK_KEYS) if (key in target) target[key] = hooks[key];
   target.Link = (hooks as any).Link;
}
