// Generated by tsr-shared-routes. Do not edit.
/* eslint-disable */
// source: src/routes/help/guides/faq.tsx
// mounts: /help/guides/faq, /inventory/help/guides/faq, /settings/guides/faq
import { makeSharedRoute } from "../../../sharedRoutes.gen";

type MountFilePaths = "/help/guides/faq" | "/inventory/help/guides/faq" | "/settings/guides/faq";

export const shared = makeSharedRoute<MountFilePaths>(
  [
  "/help/guides/faq",
  "/inventory/help/guides/faq",
  "/settings/guides/faq",
  ],
  "src/routes/help/guides/faq",
);
