import fs from "node:fs";
import path from "node:path";
import { z } from "zod";

export const DEFAULT_BANNER = "// Generated by tsr-shared-routes. Do not edit.";

/** Optional config file read from the project root by the CLI AND the vite plugin. */
export const CONFIG_FILE_NAME = "shared-routes.config.json";

/**
 * The first line of every file this tool owns. Ownership checks compare
 * against this sentinel prefix — changing `banner` still keeps the sentinel.
 */
export const BANNER_SENTINEL = "// Generated by tsr-shared-routes";

export const configSchema = z.object({
   /** Must match the TanStack Router/Start `routesDirectory`. */
   routesDirectory: z.string().default("./src/routes"),
   /**
    * Maintain a managed block in .gitignore covering generated files. On by
    * default: the plugin regenerates everything in the `config` hook of any
    * vite command (dev AND build), so generated files need not be committed.
    */
   gitignore: z.boolean().default(true),
   /** First line(s) of generated files. Must start with the sentinel. */
   banner: z
      .string()
      .default(DEFAULT_BANNER)
      .refine((b) => b.startsWith(BANNER_SENTINEL), {
         message: `banner must start with ${JSON.stringify(BANNER_SENTINEL)} so generated files stay recognizable`,
      }),
   /** Mirror of the TanStack generator options that affect file classification. */
   routeFileIgnorePrefix: z.string().default("-"),
   indexToken: z.string().default("index"),
   routeToken: z.string().default("route"),
   /** Manifest location, relative to project root. */
   manifestPath: z.string().default(".tanstack/shared-routes/manifest.json"),
});

export type SharedRoutesUserConfig = z.input<typeof configSchema>;
export type SharedRoutesConfig = z.output<typeof configSchema> & {
   /** Absolute project root all relative paths resolve against. */
   root: string;
};

export function resolveConfig(
   userConfig: SharedRoutesUserConfig | undefined,
   root: string,
): SharedRoutesConfig {
   return { ...configSchema.parse(userConfig ?? {}), root };
}

/**
 * Reads `shared-routes.config.json` from the project root; `{}` when absent.
 * Throws (with the file path in the message) on unparsable JSON — a config
 * problem should fail the run, not be silently ignored.
 */
export function readConfigFile(root: string): SharedRoutesUserConfig {
   const configPath = path.join(root, CONFIG_FILE_NAME);
   if (!fs.existsSync(configPath)) return {};
   try {
      return JSON.parse(fs.readFileSync(configPath, "utf8")) as SharedRoutesUserConfig;
   } catch (error) {
      throw new Error(
         `tsr-shared-routes: could not parse ${configPath}: ${(error as Error).message}`,
      );
   }
}

/**
 * Merges the two config sources: the file is the base, inline options win
 * per key. `conflicts` lists keys set in BOTH sources with different values
 * (same-value duplicates are harmless) so callers can surface the override —
 * silent precedence hides config edits that stopped having any effect.
 */
export function mergeConfigSources(
   fileConfig: SharedRoutesUserConfig,
   inlineConfig: SharedRoutesUserConfig,
): { merged: SharedRoutesUserConfig; conflicts: Array<string> } {
   const merged: Record<string, unknown> = { ...fileConfig };
   const conflicts: Array<string> = [];
   for (const [key, inlineValue] of Object.entries(inlineConfig)) {
      if (inlineValue === undefined) continue;
      const fileValue = (fileConfig as Record<string, unknown>)[key];
      if (key in fileConfig && JSON.stringify(fileValue) !== JSON.stringify(inlineValue)) {
         conflicts.push(
            `config ${JSON.stringify(key)}: inline sharedRoutes() value ` +
               `${JSON.stringify(inlineValue)} overrides ${CONFIG_FILE_NAME} value ` +
               `${JSON.stringify(fileValue)}`,
         );
      }
      merged[key] = inlineValue;
   }
   return { merged: merged as SharedRoutesUserConfig, conflicts };
}
