import { z } from "zod";

export const DEFAULT_BANNER = "// Generated by tsr-shared-routes. Do not edit.";

/**
 * The first line of every file this tool owns. Ownership checks compare
 * against this sentinel prefix — changing `banner` still keeps the sentinel.
 */
export const BANNER_SENTINEL = "// Generated by tsr-shared-routes";

export const configSchema = z.object({
   /** Must match the TanStack Router/Start `routesDirectory`. */
   routesDirectory: z.string().default("./src/routes"),
   /**
    * Maintain a managed block in .gitignore covering generated files. On by
    * default: the plugin regenerates everything in the `config` hook of any
    * vite command (dev AND build), so generated files need not be committed.
    */
   gitignore: z.boolean().default(true),
   /** First line(s) of generated files. Must start with the sentinel. */
   banner: z
      .string()
      .default(DEFAULT_BANNER)
      .refine((b) => b.startsWith(BANNER_SENTINEL), {
         message: `banner must start with ${JSON.stringify(BANNER_SENTINEL)} so generated files stay recognizable`,
      }),
   /** Mirror of the TanStack generator options that affect file classification. */
   routeFileIgnorePrefix: z.string().default("-"),
   indexToken: z.string().default("index"),
   routeToken: z.string().default("route"),
   /** Manifest location, relative to project root. */
   manifestPath: z.string().default(".tanstack/shared-routes/manifest.json"),
});

export type SharedRoutesUserConfig = z.input<typeof configSchema>;
export type SharedRoutesConfig = z.output<typeof configSchema> & {
   /** Absolute project root all relative paths resolve against. */
   root: string;
};

export function resolveConfig(
   userConfig: SharedRoutesUserConfig | undefined,
   root: string,
): SharedRoutesConfig {
   return { ...configSchema.parse(userConfig ?? {}), root };
}
